spring: 
  # datasource:
  #   url: jdbc:h2:
  #   username: sa                      
  #   password:                         
  #   driverClassName: org.h2.Driver    
  
  output:
    ansi:
      enabled: ALWAYS
