

insert into WAREHOUSE (id, city, state, capacity) values (1, 'Knoxville', 'TN', 655);
insert into WAREHOUSE (id, city, state, capacity) values (2, 'Hartford', 'CT', 871);
insert into WAREHOUSE (id, city, state, capacity) values (3, 'Detroit', 'MI', 915);
insert into WAREHOUSE (id, city, state, capacity) values (4, 'Jefferson City', 'MO', 830);
insert into WAREHOUSE (id, city, state, capacity) values (5, 'Rochester', 'NY', 621);
insert into WAREHOUSE (id, city, state, capacity) values (6, 'Wilmington', 'NC', 873);
insert into WAREHOUSE (id, city, state, capacity) values (7, 'Gainesville', 'FL', 673);
insert into WAREHOUSE (id, city, state, capacity) values (8, 'Apache Junction', 'AZ', 999);
insert into WAREHOUSE (id, city, state, capacity) values (9, 'Petaluma', 'CA', 783);
insert into WAREHOUSE (id, city, state, capacity) values (10, 'Spokane', 'WA', 663);



insert into APPAREL (sku, category, size, location, warehouse_id) values ('JQ-1667-GP', 'joggers', 'M', 'C3', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('ER-4682-EM', 'joggers', 'M', 'F6', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('KQ-2769-MG', 'joggers', 'S', 'B5', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('HC-2754-PH', 'shirt', 'S', 'C8', 6);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('HS-8468-LF', 'shorts', 'M', 'D2', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JM-7868-IV', 'joggers', 'L', 'D8', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EJ-8636-EZ', 'shorts', 'S', 'F7', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('HK-9095-QM', 'sweatshirt', 'S', 'A6', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('UJ-7982-GR', 'sweatshirt', 'M', 'F7', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PH-2975-MY', 'shirt', 'L', 'B5', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PT-1029-XU', 'joggers', 'S', 'B7', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('UV-5548-LZ', 'sweatshirt', 'S', 'E9', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GL-5981-QQ', 'joggers', 'M', 'C2', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('NM-6371-IY', 'shorts', 'S', 'B7', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('FQ-4991-FA', 'joggers', 'L', 'A8', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('XD-2128-BZ', 'shirt', 'M', 'D7', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WK-7215-RD', 'sweatshirt', 'L', 'C3', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PH-0773-GR', 'sweatshirt', 'S', 'D7', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WA-0922-XQ', 'shirt', 'M', 'B1', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('NA-9263-OH', 'sweatshirt', 'L', 'C7', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('YO-1546-VO', 'joggers', 'L', 'D5', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('BZ-6056-RL', 'sweatshirt', 'S', 'F3', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('TN-0526-VM', 'sweatshirt', 'M', 'A8', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EQ-9246-UM', 'shorts', 'M', 'E3', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GR-4602-MH', 'shirt', 'L', 'F8', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('MU-3264-DP', 'shirt', 'L', 'A6', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('OL-5855-WG', 'shirt', 'L', 'D3', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GX-1632-WZ', 'sweatshirt', 'S', 'F5', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('SY-8548-RY', 'shirt', 'M', 'A1', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('HP-4055-IA', 'sweatshirt', 'M', 'E5', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('CJ-5437-GB', 'joggers', 'L', 'E6', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('VA-4089-LX', 'joggers', 'M', 'F2', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GE-9416-DX', 'joggers', 'M', 'A7', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GQ-1710-DV', 'sweatshirt', 'S', 'C2', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PA-2151-PW', 'sweatshirt', 'S', 'B1', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('AE-9446-OW', 'shorts', 'M', 'F2', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('UQ-0110-KS', 'shirt', 'M', 'F1', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('HR-0371-MK', 'shirt', 'L', 'A6', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('DU-6027-LJ', 'shirt', 'L', 'C3', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('UN-7824-FD', 'shorts', 'S', 'E6', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('ID-4310-XG', 'shorts', 'L', 'F3', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('KG-6499-VX', 'joggers', 'L', 'F9', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GF-1084-SD', 'shirt', 'M', 'D3', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EA-6895-CK', 'shorts', 'L', 'E2', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('YS-5204-OJ', 'shirt', 'L', 'D5', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EQ-8169-ZJ', 'joggers', 'S', 'B9', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('KK-8584-XN', 'joggers', 'L', 'D2', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('ZL-1932-PM', 'sweatshirt', 'M', 'D4', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('RL-3013-XI', 'sweatshirt', 'M', 'A1', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('XE-6762-PQ', 'joggers', 'S', 'D4', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('OZ-0247-ON', 'sweatshirt', 'L', 'D4', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JU-4671-UK', 'joggers', 'M', 'C3', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('KI-0100-FO', 'joggers', 'S', 'D1', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('QO-9696-ZK', 'sweatshirt', 'M', 'D7', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('NA-4648-BP', 'sweatshirt', 'S', 'B5', 6);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GZ-9094-ER', 'joggers', 'S', 'E7', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JW-2749-QC', 'joggers', 'M', 'A1', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('XI-6166-GN', 'sweatshirt', 'L', 'A5', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('LP-2867-MU', 'joggers', 'S', 'C9', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JE-6218-EE', 'sweatshirt', 'M', 'A4', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JT-4971-YG', 'shirt', 'S', 'D3', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('VY-3992-WY', 'shorts', 'M', 'F2', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('OW-4278-UD', 'shirt', 'M', 'A6', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PP-3408-MN', 'sweatshirt', 'S', 'B4', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('ML-4482-GJ', 'shorts', 'S', 'A2', 6);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('CB-6625-QA', 'sweatshirt', 'L', 'E6', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('GP-9987-SZ', 'joggers', 'S', 'A5', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('CH-0263-ML', 'sweatshirt', 'M', 'E3', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('RC-6719-MZ', 'joggers', 'L', 'B8', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('DE-5806-GY', 'shorts', 'M', 'D8', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EE-3951-HS', 'sweatshirt', 'S', 'B1', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('AS-6168-JU', 'joggers', 'L', 'C8', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('TJ-2093-QO', 'sweatshirt', 'M', 'C1', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('LX-1652-IJ', 'sweatshirt', 'L', 'F8', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('II-1528-CF', 'joggers', 'M', 'B8', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('YY-0803-JR', 'shorts', 'S', 'A7', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JC-9727-HQ', 'shorts', 'L', 'C8', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('SI-8170-KF', 'joggers', 'S', 'B6', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('UI-2284-DC', 'shorts', 'S', 'C3', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('JT-4560-BY', 'shorts', 'S', 'C3', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('PF-9857-CM', 'shirt', 'M', 'F8', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WD-6496-OB', 'sweatshirt', 'L', 'C7', 6);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('CI-9563-LV', 'joggers', 'M', 'B2', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('YX-7392-XN', 'joggers', 'M', 'A3', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EL-0772-OQ', 'sweatshirt', 'M', 'B1', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('EO-6273-YX', 'joggers', 'M', 'E6', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('IU-1647-OY', 'shorts', 'S', 'D6', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('TK-0814-WI', 'sweatshirt', 'S', 'A4', 4);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('CL-7747-AJ', 'shirt', 'L', 'C4', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('QF-4989-ET', 'shorts', 'L', 'E2', 1);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('ZC-6780-OW', 'joggers', 'S', 'D1', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('NN-0448-OF', 'shirt', 'L', 'A4', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WQ-4611-VL', 'shirt', 'L', 'B5', 8);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WS-4120-UC', 'joggers', 'S', 'D8', 7);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('KL-5856-BL', 'joggers', 'L', 'B9', 5);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('WK-3798-DI', 'shorts', 'L', 'F2', 3);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('XU-1682-BZ', 'shorts', 'S', 'C4', 2);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('BD-4580-UW', 'joggers', 'L', 'D8', 9);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('QX-3708-AI', 'shirt', 'M', 'C3', 10);
insert into APPAREL (sku, category, size, location, warehouse_id) values ('RM-0797-RM', 'shirt', 'M', 'A6', 7);

